### ISSUE TITLE
ValueError: The SVG size is undefined

### ISSUE THREAD

**Issue by Idontgivefuck** [Bbalduzz/Kitaboo-PDF-Downloader#1]
[+] Enter book URL (search toc.xml): 
https://webreader.zanichelli.it/2131252/html5/2131252/OPS

[+] Book Found:
    - title: Matematica.blu 1
    - description: Terza edizione
    - author: Bergamini, Barozzi, Trifone
    - isbn: 1337808291745
    - pages: 951

[+] Downloading book... |----------------------------------------------------------------------------------------------------| 0.00%
Traceback (most recent call last):
  File "C:\Users\39333\Desktop\Kitaboo-PDF-Downloader-main\zncDL.py", line 104, in <module>
    download_and_create()
  File "C:\Users\39333\Desktop\Kitaboo-PDF-Downloader-main\zncDL.py", line 76, in download_and_create
    cairosvg.svg2pdf(url=f'pages/page{n:04d}_student.svg', write_to=f'pdfs/page{n:04d}_student.pdf')
  File "D:\Python\Python311\Lib\site-packages\cairosvg\__init__.py", line 67, in svg2pdf
    return surface.PDFSurface.convert(
  File "D:\Python\Python311\Lib\site-packages\cairosvg\surface.py", line 131, in convert
    instance = cls(
  File "D:\Python\Python311\Lib\site-packages\cairosvg\surface.py", line 207, in __init__
    raise ValueError('The SVG size is undefined')
ValueError: The SVG size is undefined

Ciao, come mostrato sopra, purtroppo, quando vado ad incollare il link per scaricare le pagine ricevo il seguente errore. Se negli errori vedi "_student.svg" anzichè semplicemente svg è perchè ho modificato lo script, poichè, avendo una versione del libro annotta il file che voglio che venga scaricato finisce in _student.svg e non semplicemente .svg. Potresti spiegarmi come risolvere quest'errore o, in alternativa, dandoti il link del Kitaboo scaricarmelo direttamente tu e poi passarmelo tramite Telegram o qualsiasi altro mezzo?
Grazie mille!

**Comment by Bbalduzz** [comment]
hey ciao! Grazie per aver segnalato il problema, è un po' che non uso lo script. Da quanto vedo hanno cambiato il reader. Ci smanetto un po' e ti faccio sapere ;)

**Comment by Bbalduzz** [comment]
alla fine ho cambiato tutto. Ora non dovrebbe darti più quel problema. Prima di eseguirlo ricordati di fare il cambiamento che avevi fatto nello script passato e di scaricare le librerie necessarie.

**Comment by Idontgivefuck** [comment]
Okk grazie mille, gentilissimo!
